# Setup
title:               A living literature review of Large Language Models
tagline:             'a living literature review'
description:         'Research on Large Language Models.'
url:                 https://llm-bible.github.io
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/ 

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
