# Setup
title:               A living literature review for the Large Language Model field
tagline:             'a living literature review'
description:         'Research on Large Language Models.'
url:                 https://llm-papers.github.io
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
